### ISSUE TITLE
Window_Windows::init() does not allow to skip initialization for m_userProvidedWindowHandle

### ISSUE THREAD

**Issue by ManuelKugelmann** [COVESA/ramses#58]
The supplied handle may be of a pre-initialized Window that does not want any changes

**Comment by violinyanev** [comment]
Hi @ManuelKugelmann I assume with initialization you mean the init() method, right? I guess we can do this, but we need to discuss internally how to handle the case where other settings have been provided (e.g. width/height of window). What behavior would you expect?

**Comment by ManuelKugelmann** [comment]
@violinyanev A variant of my ramses Unity3D integration directly injects a external FrameBufferObject into Device_GL and this comes from the original Unity3D context / window which ramses should not modify. I have decided to deprecate this variant in favor of the more general Spout based integration.
